site_name: WordOps Documentation
site_description: Wordops documentation and user guides
copyright: 'Copyright &copy; 2019 WordOps - <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img style="display:inline;" alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>'
repo_url: https://github.com/WordOps/WordOps/
edit_uri: "https://github.com/WordOps/docs.wordops.net/edit/master/docs/"
remote_branch: gh-pages

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'
  highlightjs: true

markdown_extensions:
  # Code highlighting in ``` ``` blocks
  - codehilite:
      guess_lang: true
# Table of Contents
  - toc:
      permalink: true
# block div
  - admonition
  - meta

extra_css:
  - css/extra.css

nav:
- Home: 'README.md'
- Getting Started:
  - Prerequisites: 'getting-started/prerequesites.md'
  - Installation: 'getting-started/installation-guide.md'
  - Post-install steps: 'getting-started/post-install-steps.md'
  - Creating sites: 'getting-started/creating-sites.md'
- Commands:
  - Overview: 'commands.md'
  - site: 'commands/site.md'
  - stack: 'commands/stack.md'
  - debug: 'commands/debug.md'
  - clean: 'commands/clean.md'
  - info: 'commands/info.md'
  - log: 'commands/log.md'
  - secure: 'commands/secure.md'
  - maintenance: 'commands/maintenance.md'
  - update: 'commands/update.md'
- How to :
  - Overview: 'how-to.md'
  - Set WordPress language: 'how-to/wp-language.md'
  - Secure WordOps backend: 'how-to/secure-22222.md'
- Guides:
  - Overview: 'guides.md'
  - EasyEngine Migration: 'guides/migration-from-easyengine.md'
- F.A.Q: 'faq.md'
- Community:
  - WordOps.net: https://wordops.net
  - Community forum: https://community.wordops.net
  - Slack: https://community.wordops.io/slack
  - Twitter: https://twitter.com/WordOps_
  - Mastodon: https://mastodon.top/@WordOps



extra:
  social:
    - type: globe
      link: https://wordops.net
    - type: github-alt
      link: https://github.com/WordOps
    - type: twitter
      link: https://twitter.com/WordOps_
    - type: slack
      link: https://community.wordops.io/slack
    - type: comments
      link: https://community.wordops.net