site_name: Docs WordOps
site_description: Wordops documentation and user guides
repo_url: https://github.com/WordOps/WordOps/
edit_uri: "https://github.com/WordOps/docs.wordops.io/edit/master/docs/"

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'

nav:
- Home: 'README.md'
- Getting Started: 'getting-started.md'
- Installation Guide: 'installation-guide.md'
- Commands:
    - Overview: 'commands/#overview'
    - site: 'commands/#site'
    - stack: 'commands/#stack'
    - update: 'commands/#update'
- F.A.Q: 'faq.md'
