site_name: Docs WordOps
site_description: Wordops documentation and user guides
copyright: 'Copyright &copy; 2019 WordOps'
repo_url: https://github.com/WordOps/WordOps/
edit_uri: "https://github.com/WordOps/docs.wordops.net/edit/master/docs/"
remote_branch: gh-pages

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'
  highlightjs: true

markdown_extensions:
  - toc:
      permalink: true

extra_css:
  - css/extra.css

nav:
- Home: 'README.md'
- Getting Started:
  - Quick start: 'getting-started.md'
  - Installation Guide: 'installation-guide.md'
  - Migration from EasyEngine: 'migration-from-EasyEngine-V3.md'
- Commands:
  - Overview: 'commands.md'
  - site: 'commands/site.md'
  - stack: 'commands/stack.md'
  - debug: 'commands/debug.md'
  - clean: 'commands/clean.md'
  - info: 'commands/info.md'
  - log: 'commands/log.md'
  - secure: 'commands/secure.md'
  - maintenance: 'commands/maintenance.md'
  - update: 'commands/update.md'
- F.A.Q: 'faq.md'

extra:
  social:
    - type: globe
      link: https://wordops.net
    - type: github-alt
      link: https://github.com/WordOps
    - type: twitter
      link: https://twitter.com/WordOps_
    - type: slack
      link: https://community.wordops.io/slack
    - type: comments
      link: https://community.wordops.net