site_name: Docs WordOps
site_description: Wordops documentation and user guides
repo_url: https://github.com/WordOps/WordOps/
edit_uri: "https://github.com/WordOps/docs.wordops.net/edit/master/docs/"

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'

extra_css:
  - css/extra.css

nav:
- Home: 'README.md'
- Getting Started: 'getting-started.md'
- Installation Guide: 'installation-guide.md'
- Commands:
  - Overview: 'commands.md'
  - site: 'commands/site.md'
  - stack: 'commands/stack.md'
  - debug: 'commands/debug.md'
  - clean: 'commands/clean.md'
  - info: 'commands/info.md'
  - log: 'commands/log.md'
  - secure: 'commands/secure.md'
  - maintenance: 'commands/maintenance.md'
  - update: 'commands/update.md'
- F.A.Q: 'faq.md'
