site_name: Docs WordOps
repo_url: https://github.com/WordOps/WordOps/
edit_uri: ""

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'

nav:
  - Home: 'README.md'
  - Getting Started: 'getting-started.md'
  - WordOps commands: 'commands.md'
  - F.A.Q: 'faq.md'
